### ISSUE TITLE
Jesse's question about URL

### ISSUE THREAD

**Issue by pedrojovelli** [robanquieri/rioslumstudio#19]
http://rioslumstudio.com/#/

Is there a spefic reason for this # at the end of the address? 

If there's a way to get rid of that.

**Comment by robanquieri** [comment]
The hash is used in single page applications, so instead of using it to navigate to a point in a page you use the hash as a means to navigate from page to page. The advantage of this is that it does not require a refresh page. Rioslum's website is built as SPA, which means it is not possible to remove the hash because it ir part of router core.
